/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fernando;

public class Library {
    /**
     * Faz alguma coisa
     * @return
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
